###
GET http://localhost:3500/api/auth/current-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU0NjY3MmJkLTA4ODctNDFhZC1hZjMxLTljMDc0YTMwMzY5MSIsImNyZWF0ZWRBdCI6IjIwMjItMTEtMDhUMDU6MDA6MTAuMDAyWiIsInVwZGF0ZWRBdCI6IjIwMjItMTEtMDhUMDU6MDA6MTAuMDAyWiIsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJHYWdhbiIsImxhc3ROYW1lIjoiU2luZ2giLCJyb2xlIjoiVVNFUiIsImlhdCI6MTY2Nzg2NTY2NCwiZXhwIjoxNjY3OTUyMDY0fQ.FA4DUzvm2SM6HsJNnQ_E-IqBk8uNHifuKK-TBW_hKw6YPRIdcLiGMtapqZUWEdjHC8b55DNmCq-1mi4KlxWVYw