###
GET http://localhost:3500/api/auth/current-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmMDFlYTJjLTU2NjEtNDY1OS04ODFjLTE0OTgwYTM2MTRhZiIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjZUMDc6MTQ6MTQuNzU4WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjZUMDc6MTQ6MTQuNzU4WiIsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJHYWdhbiIsImxhc3ROYW1lIjoiU2luZ2giLCJpYXQiOjE2NjY3NTUwMzgsImV4cCI6MTY2Njg0MTQzOH0.ANnlje65WJSa7gBhQsP4aH6Rv5AaxectXEzWdUmuxo7SdvYDMJPx7g5UM3dnYBghw88j9SPJ9_mtp_TS2QTJkw